# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teyco', '0003_auto_20171101_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandat',
            name='periode',
            field=models.CharField(max_length=50),
        ),
    ]
